### ISSUE TITLE
is there a python3?

### ISSUE THREAD

**Issue by initial-h** [stranskyjan/pbrain-pyrandom#1]
I write my AI with tensorflow and python3, is there a .py for python3?thank u

**Comment by stranskyjan** [comment]
Hello, thanks for a good point. I modified the code, it works now also with Python3 (tested on win7). If you have any problem, please let me know

**Comment by initial-h** [comment]
Thank you for your help and there's something wrong with tensorflow.
I add tensorflow to the example.py (import tensorflow as tf) to test if it works, it doesn't.
I don't change any other code ,and pyinstaller it to exe, link with piskvork.exe and the wrong info as follow

![1524017385 1](https://user-images.githubusercontent.com/27199383/38907931-aded62da-42f0-11e8-87b0-724c0feec614.png)

then ,I .\pbrain-pyrandom.exe in windows powershell, ModuleNotFoundError arise:

PS D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\dist> .\pbrain-pyrandom.exe
Traceback (most recent call last):
  File "example.py", line 4, in <module>
ModuleNotFoundError: No module named 'tensorflow'
[2092] Failed to execute script example

but my env really have installed tensorflow, I don't know if there's something wrong with pyinstaller.exe, thre's my pyinstaller info:

PS D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom> pyinstaller.exe example.py pisqpipe.py --name pbrain-pyrandom.exe --onefile
359 INFO: PyInstaller: 3.3.1
359 INFO: Python: 3.6.0
359 INFO: Platform: Windows-10-10.0.16299-SP0
359 INFO: wrote D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\pbrain-pyrandom.exe.spec
359 INFO: UPX is not available.
375 INFO: Extending PYTHONPATH with paths
['D:\\wakaka\\intern\\DL_model\\gomoku\\pbrain-pyrandom',
 'D:\\wakaka\\intern\\DL_model\\gomoku\\pbrain-pyrandom',
 'D:\\wakaka\\intern\\DL_model\\gomoku\\pbrain-pyrandom']
375 INFO: checking Analysis
375 INFO: Building Analysis because out00-Analysis.toc is non existent
375 INFO: Initializing module dependency graph...
375 INFO: Initializing module graph hooks...
375 INFO: Analyzing base_library.zip ...
4437 INFO: running Analysis out00-Analysis.toc
4437 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\software\python3\python.exe
5203 INFO: Caching module hooks...
5203 INFO: Analyzing D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\example.py
5234 INFO: Analyzing D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\pisqpipe.py
5250 INFO: Loading module hooks...
5250 INFO: Loading module hook "hook-encodings.py"...
5391 INFO: Loading module hook "hook-pydoc.py"...
5406 INFO: Loading module hook "hook-pywintypes.py"...
5844 INFO: Loading module hook "hook-xml.py"...
6141 INFO: Looking for ctypes DLLs
6141 INFO: Analyzing run-time hooks ...
6156 INFO: Looking for dynamic libraries
6344 INFO: Looking for eggs
6344 INFO: Using Python library d:\software\python3\python36.dll
6344 INFO: Found binding redirects:
[]
6360 INFO: Warnings written to D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\build\pbrain-pyrandom.exe\warnpbrain-pyrandom.exe.txt
6406 INFO: Graph cross-reference written to D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\build\pbrain-pyrandom.exe\xref-pbrain-pyrandom.exe.html
6453 INFO: checking PYZ
6453 INFO: Building PYZ because out00-PYZ.toc is non existent
6469 INFO: Building PYZ (ZlibArchive) D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\build\pbrain-pyrandom.exe\out00-PYZ.pyz
7157 INFO: Building PYZ (ZlibArchive) D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\build\pbrain-pyrandom.exe\out00-PYZ.pyz completed successfully.
7172 INFO: checking PKG
7172 INFO: Building PKG because out00-PKG.toc is non existent
7172 INFO: Building PKG (CArchive) out00-PKG.pkg
8999 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
9002 INFO: Bootloader d:\software\python3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
9003 INFO: checking EXE
9005 INFO: Building EXE because out00-EXE.toc is non existent
9006 INFO: Building EXE from out00-EXE.toc
9007 INFO: Appending archive to EXE D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\dist\pbrain-pyrandom.exe
9014 INFO: Building EXE from out00-EXE.toc completed successfully.

thanks again~
PS: my machine is win10, I think it's not the reason.

**Comment by initial-h** [comment]
I add a path by:
pyinstaller.exe example.py pisqpipe.py --name pbrain-pyrandom.exe --onefile -p D:\software\Python3\Lib\site-packages\tensorflow\;

some other error arise:

PS D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom> pyinstaller.exe example.py pisqpipe.py --name pbrain-pyrandom.exe --onefile -p D:\software\Python3\Lib\site-packages\tensorflow\;
375 INFO: PyInstaller: 3.3.1
375 INFO: Python: 3.6.0
375 INFO: Platform: Windows-10-10.0.16299-SP0
375 INFO: wrote D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\pbrain-pyrandom.exe.spec
390 INFO: UPX is not available.
390 INFO: Extending PYTHONPATH with paths
['D:\\wakaka\\intern\\DL_model\\gomoku\\pbrain-pyrandom',
 'D:\\wakaka\\intern\\DL_model\\gomoku\\pbrain-pyrandom',
 'D:\\software\\Python3\\Lib\\site-packages\\tensorflow',
 'D:\\wakaka\\intern\\DL_model\\gomoku\\pbrain-pyrandom']
390 INFO: checking Analysis
390 INFO: Building Analysis because out00-Analysis.toc is non existent
390 INFO: Initializing module dependency graph...
390 INFO: Initializing module graph hooks...
390 INFO: Analyzing base_library.zip ...
4359 INFO: running Analysis out00-Analysis.toc
4375 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\software\python3\python.exe
5109 INFO: Caching module hooks...
5125 INFO: Analyzing D:\wakaka\intern\DL_model\gomoku\pbrain-pyrandom\example.py
6864 INFO: Processing pre-find module path hook   distutils
8098 INFO: Processing pre-find module path hook   site
8098 INFO: site: retargeting to fake-dir 'd:\\software\\python3\\lib\\site-packages\\PyInstaller\\fake-modules'
17168 INFO: Processing pre-safe import module hook   six.moves
32186 INFO: Processing pre-safe import module hook   requests.packages.urllib3.packages.six.moves
33373 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
Traceback (most recent call last):
  File "d:\software\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\software\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\software\Python3\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "d:\software\python3\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\software\python3\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\software\python3\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\software\python3\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "d:\software\python3\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "d:\software\python3\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()

...(many info similar to above)....

  File "d:\software\python3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 965, in visit_FunctionDef
    self.generic_visit(node)
  File "d:\software\python3\lib\ast.py", line 261, in generic_visit
    self.visit(item)
  File "d:\software\python3\lib\ast.py", line 253, in visit
    return visitor(node)
  File "d:\software\python3\lib\ast.py", line 263, in generic_visit
    self.visit(value)
  File "d:\software\python3\lib\ast.py", line 253, in visit
    return visitor(node)
  File "d:\software\python3\lib\ast.py", line 263, in generic_visit
    self.visit(value)
  File "d:\software\python3\lib\ast.py", line 253, in visit
    return visitor(node)
  File "d:\software\python3\lib\ast.py", line 263, in generic_visit
    self.visit(value)
  File "d:\software\python3\lib\ast.py", line 253, in visit
    return visitor(node)
  File "d:\software\python3\lib\ast.py", line 257, in generic_visit
    for field, value in iter_fields(node):
RecursionError: maximum recursion depth exceeded

**Comment by stranskyjan** [comment]
Hello,
after some googling, it seems that the problem is in the combination of PyInstaller and the version of Python, see e.g. [1].
What Python version do you use?

[1] https://www.bountysource.com/issues/50239952-recursionerror-maximum-recursion-depth-exceeded-python-3-6-issue

**Comment by initial-h** [comment]
thank u a lot!
I try python3.5 and it work .
next step I'll study the protocol and put my model in it.really thanks!
