### ISSUE TITLE
are there some good ways to debug?

### ISSUE THREAD

**Issue by initial-h** [stranskyjan/pbrain-pyrandom#2]
hi,
  I pyinstall my model to exe,but there are some bugs.
  And it's not easy to debug,because the exe can only run in piskvork.exe, the bug information is always the same.like
![1524637749 1](https://user-images.githubusercontent.com/27199383/39229368-194835d8-4895-11e8-9754-3537b1afc910.jpg)
is there a way that i can print concrete error info like in python console?

**Comment by stranskyjan** [comment]
Hello,
sorry for late answer.
I have tried several approaches, but finally the only working is to write messages to an external file. Have a look at example.py at the end, where brain_turn might be redefined to raise an error and there is an example how to get this error.
Not tested in Python 3, but should work. Let me know
Thanks
Jan
