### ISSUE TITLE
Pbrain stdin read problem

### ISSUE THREAD

**Issue by ZodiacFRA** [stranskyjan/pbrain-pyrandom#3]
Hello,

I found your neat code on github and I'm currently trying to create a pbrain for Pyskvorky as well, but I have a strange problem would you mind helping me a bit?

I'm using win10 and python 3.7.0 with pyinstaller 3.4
Sending commands to Pyskvorky works, but I'm struggling reading from stdin.
I'm using sys.stdin.readline().strip() as you do.
However the call of readline is blocked until Pyskvorky declares a timeout on my executable and close it, and only at this moment I receive the "START 20" initially sent by Pyskvorky

I know you're using win32process but the documentation is nearly non-existing so i'm sticking to python threading.Thread objects and Queues for interThread communication.
It's working fine: readline works and fill the Queue with the command, which is read successfully by the other thread (you can see this using the Pyskvorky logs with DEBUG enabled after the timeout)

I don't get how the thread object would prevent python from reading stdin, I've tried read(), input() etc instead of readline and it's not working either so if you have any ideas I'll take it!
I've joined the script and build files if you want to take a deeper look: 
http://fromsmash.com/652da808-d2ca-11e8-95d3-06812412be8a

Thanks for your time and have a nice day

**Comment by stranskyjan** [comment]
Hello,
thanks for the clear problem description and the code, I have tried it and reproduced what you have described, the code "blocks" just at the sys.stdin.readline()
I have very little experience with python threading and will be of no help in this case.. 
I **guess**, in my case it works because of the STD_INPUT_HANDLE.
cheers
Jan

**Comment by ZodiacFRA** [comment]
Hello, 
Thanks for your help, I've finally resolved the problem by calling sys.stdin.readline() from the main thread.
I don't know why that worked however because this is not a problem for writing to stdout!

Have a great day, thank you again!

**Comment by stranskyjan** [comment]
ok :-)
for backward reference, the problem was not related to pbrain-pyrandom but to ZodiacFRA's own code.
